<a href="https://colab.research.google.com/github/Hari25483/PyTorch/blob/main/CO544_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!conda create -n pytorch_env python=3.7 -y

/bin/bash: conda: command not found


In [4]:
!pip install pytorch torchvision torchaudio cudatoolkit pytorch 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement cudatoolkit (from versions: none)
ERROR: No matching distribution found for cudatoolkit


In [1]:
import torch
import numpy as np

In [2]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

In [3]:
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [4]:
# x_ones = torch.z_like(x_data) # retains the properties of x_data
# print(f"Ones Tensor: \n {x_ones} \n")
x_ones=torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [5]:
x_zeros=torch.zeros_like(x_data)
print(x_zeros)

tensor([[0, 0],
        [0, 0]])


In [6]:
x_rand=torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[0.5637, 0.5928],
        [0.8435, 0.9685]])


In [7]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9290, 0.1592, 0.5016],
        [0.8385, 0.0900, 0.8860]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
tensor=torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [10]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

In [25]:
tensor = torch.rand(4, 4,dtype=torch.float)
print(tensor[0])
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0

print(tensor)

tensor([0.9586, 0.9874, 0.1729, 0.3786])
First row: tensor([0.9586, 0.9874, 0.1729, 0.3786])
First column: tensor([0.9586, 0.9946, 0.2319, 0.0206])
Last column: tensor([0.3786, 0.2163, 0.6204, 0.5266])
tensor([[0.9586, 0.0000, 0.1729, 0.3786],
        [0.9946, 0.0000, 0.1479, 0.2163],
        [0.2319, 0.0000, 0.4790, 0.6204],
        [0.0206, 0.0000, 0.3314, 0.5266]])


In [26]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[0.9586, 0.0000, 0.1729, 0.3786],
        [0.9946, 0.0000, 0.1479, 0.2163],
        [0.2319, 0.0000, 0.4790, 0.6204],
        [0.0206, 0.0000, 0.3314, 0.5266]]) 

tensor([[5.9586, 5.0000, 5.1729, 5.3786],
        [5.9946, 5.0000, 5.1479, 5.2163],
        [5.2319, 5.0000, 5.4790, 5.6204],
        [5.0206, 5.0000, 5.3314, 5.5266]])


In [28]:
# This computes the matrix multiplication between two tensors.
# y1, y2, y3 will have the same value
# ‘‘tensor.T‘‘ returns the transpose of a tensor
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)
y3 = torch.rand_like(y1)
print(y3)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[116.1933, 115.4053, 114.7472, 112.2202],
        [115.4053, 114.6455, 113.8860, 111.3703],
        [114.7472, 113.8860, 113.9812, 111.5399],
        [112.2202, 111.3703, 111.5399, 109.1739]])
tensor([[116.1933, 115.4053, 114.7472, 112.2202],
        [115.4053, 114.6455, 113.8860, 111.3703],
        [114.7472, 113.8860, 113.9812, 111.5399],
        [112.2202, 111.3703, 111.5399, 109.1739]])
tensor([[0.6953, 0.2012, 0.6793, 0.4529],
        [0.0504, 0.7091, 0.0106, 0.6072],
        [0.9006, 0.5963, 0.8599, 0.5267],
        [0.7987, 0.1368, 0.9032, 0.7802]])


tensor([[116.1933, 115.4053, 114.7472, 112.2202],
        [115.4053, 114.6455, 113.8860, 111.3703],
        [114.7472, 113.8860, 113.9812, 111.5399],
        [112.2202, 111.3703, 111.5399, 109.1739]])

In [29]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[35.5049, 25.0000, 26.7592, 28.9293],
        [35.9354, 25.0000, 26.5008, 27.2093],
        [27.3730, 25.0000, 30.0195, 31.5888],
        [25.2064, 25.0000, 28.4241, 30.5434]])

### OCR 

In [32]:
import torch
import torchvision
import numpy as np
import torch.nn as nn
import matplotlib.pyplot as pip
from torch.utils.data import DataLoader
import torchvision.transforms as transforms

In [38]:
# train_dataset = torchvision.datasets.MNIST(root='./data',train=True,download=True,transform=transforms.ToTensor())
train_dataset=torchvision.datasets.MNIST(root='./data',train=True, download=True,transform=transforms.ToTensor())