<a href="https://colab.research.google.com/github/Hari25483/PyTorch/blob/main/CO544_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!conda create -n pytorch_env python=3.7 -y

/bin/bash: conda: command not found


In [4]:
!pip install pytorch torchvision torchaudio cudatoolkit pytorch 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement cudatoolkit (from versions: none)
ERROR: No matching distribution found for cudatoolkit


In [1]:
import torch
import numpy as np

In [2]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

In [3]:
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [4]:
# x_ones = torch.z_like(x_data) # retains the properties of x_data
# print(f"Ones Tensor: \n {x_ones} \n")
x_ones=torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [5]:
x_zeros=torch.zeros_like(x_data)
print(x_zeros)

tensor([[0, 0],
        [0, 0]])


In [6]:
x_rand=torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[0.5637, 0.5928],
        [0.8435, 0.9685]])


In [7]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9290, 0.1592, 0.5016],
        [0.8385, 0.0900, 0.8860]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
tensor=torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [10]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

In [25]:
tensor = torch.rand(4, 4,dtype=torch.float)
print(tensor[0])
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0

print(tensor)

tensor([0.9586, 0.9874, 0.1729, 0.3786])
First row: tensor([0.9586, 0.9874, 0.1729, 0.3786])
First column: tensor([0.9586, 0.9946, 0.2319, 0.0206])
Last column: tensor([0.3786, 0.2163, 0.6204, 0.5266])
tensor([[0.9586, 0.0000, 0.1729, 0.3786],
        [0.9946, 0.0000, 0.1479, 0.2163],
        [0.2319, 0.0000, 0.4790, 0.6204],
        [0.0206, 0.0000, 0.3314, 0.5266]])
