<a href="https://colab.research.google.com/github/Hari25483/PyTorch/blob/main/CO544_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!conda create -n pytorch_env python=3.7 -y

/bin/bash: conda: command not found


In [4]:
!pip install pytorch torchvision torchaudio cudatoolkit pytorch 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement cudatoolkit (from versions: none)
ERROR: No matching distribution found for cudatoolkit


In [5]:
import torch
import numpy as np

In [11]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

In [14]:
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [17]:
# x_ones = torch.z_like(x_data) # retains the properties of x_data
# print(f"Ones Tensor: \n {x_ones} \n")
x_ones=torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [18]:
x_zeros=torch.zeros_like(x_data)
print(x_zeros)

tensor([[0, 0],
        [0, 0]])


In [23]:
x_rand=torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[0.1410, 0.8052],
        [0.9001, 0.4010]])


In [27]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3989, 0.0514, 0.0697],
        [0.3493, 0.6444, 0.6343]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [29]:
tensor=torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
